[build]
  builder = "nixpacks"
  buildCommand = "npm run build"
  installCommand = "composer install --optimize-autoloader --no-dev && npm install"
  startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT}"
  nixPkgs = ['php82', 'php82Extensions.curl', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.openssl', 'php82Extensions.json', 'php82Extensions.tokenizer', 'php82Extensions.pdo', 'php82Extensions.gd', 'php82Extensions.fileinfo', 'php82Extensions.zip', 'php82Extensions.exif', 'php82Extensions.sodium', 'php82Extensions.pdo_mysql', 'nodejs-18_x', 'yarn']
  
[deploy]
  startTimeout = 30
  healthcheckPath = "/"
  healthcheckTimeout = 30
  restartDelay = 5
  restartMaxRetries = 10
  restartTimeout = 60
