[build]
# Install PHP + Node dependencies and build React frontend
installCommand = "composer install --no-dev --optimize-autoloader && npm ci --omit=dev && npm run build"


[start]
command = ""

[env]
# Laravel App
APP_NAME = "Laravel"
APP_ENV = "production"
APP_KEY = "base64:PRMgg8BebBCOjKNOW2jG1DZ93EAON+FoDUgq5fQ8Gd8="
APP_DEBUG = "false"
APP_URL = "https://uddsems-production.up.railway.app"
