[build]
installCommand = "composer install --no-dev --optimize-autoloader && npm ci --omit=dev && npm run build"
buildCommand = ""
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

[deploy]
commands = [
  "php artisan migrate --force",
  "php artisan optimize"
]
