[build]
# Install PHP + Node dependencies and build React frontend
installCommand = "composer install --no-dev --optimize-autoloader && npm ci --omit=dev && npm run build"


[start]
command = "php -S 0.0.0.0:$PORT -t public"

[env]
# Laravel App
APP_NAME = "Laravel"
APP_ENV = "production"
APP_KEY = "base64:PRMgg8BebBCOjKNOW2jG1DZ93EAON+FoDUgq5fQ8Gd8="
APP_DEBUG = "false"
APP_URL = "https://<YOUR_RAILWAY_APP>.up.railway.app"

# Database
DB_CONNECTION = "mysql"
DB_HOST = "mysql.railway.internal"
DB_PORT = "3306"
DB_DATABASE = "railway"
DB_USERNAME = "root"
DB_PASSWORD = "<RAILWAY_MYSQL_PASSWORD>"

# Session & Cache
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"
QUEUE_CONNECTION = "database"

# React + Vite
VITE_APP_NAME = "Laravel"
