[build]
  builder = "nixpacks"
  buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && \
                 npm install && \
                 npm run build && \
                 php artisan storage:link && \
                 php artisan optimize:clear"
  
  [build.nixpacksPlan.phases.one]
    nixPkgs = [
      "php83"
      "php83.extensions.curl"
      "php83.extensions.mbstring"
      "php83.extensions.openssl"
      "php83.extensions.pdo"
      "php83.extensions.pdo_mysql"
      "php83.extensions.mysqlnd"
      "php83.extensions.tokenizer"
      "php83.extensions.xml"
      "php83.extensions.zip"
      "php83.extensions.gd"
      "php83.extensions.fileinfo"
      "composer"
      "nodejs-18_x"
      "yarn"
    ]
    cmds = [
      "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev",
      "npm install",
      "npm run build"
    ]
  
  [build.nixpacksPlan.start]
    cmd = "/app/vendor/bin/heroku-php-apache2 public/"

[deploy]
  startCommand = "php artisan migrate --force && /app/vendor/bin/heroku-php-apache2 public/"

[environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  COMPOSER_MEMORY_LIMIT = "-1"
  PHP_INI_MEMORY_LIMIT = "256M"
  PHP_INI_UPLOAD_MAX_FILESIZE = "64M"
  PHP_INI_POST_MAX_SIZE = "64M"
  PHP_INI_MAX_EXECUTION_TIME = "300"

[variables]
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_KEY = { as = "APP_KEY", generate = "php -r \"echo 'base64:'.base64_encode(random_bytes(32)).PHP_EOL;\"" }
  APP_URL = ""
  
  DB_CONNECTION = "mysql"
  
  # Cache
  CACHE_DRIVER = "redis"
  SESSION_DRIVER = "redis"
  QUEUE_CONNECTION = "redis"
  
  # Mail
  MAIL_MAILER = "smtp"
  
[healthcheck]
  enabled = true
  interval = 5
  timeout = 30
  start_period = 30
  retries = 5