[build]
installCommand = "composer install --no-dev --optimize-autoloader && npm ci && npm run build"

[build.environment]
RAILS_ENV = "production"

[start]
# Use Laravel's built-in server (development only) OR point to Apache/Nginx in production
# Railway recommends PHP server via Nixpacks
command = "php artisan serve --host=0.0.0.0 --port=8080"

[env]
APP_NAME = "SEMS"
APP_ENV = "production"
APP_KEY = "base64:PRMgg8BebBCOjKNOW2jG1DZ93EAON+FoDUgq5fQ8Gd8="
APP_DEBUG = "false"
APP_URL = "https://uddsems-production.up.railway.app"

# Database (Railway MySQL)
DB_CONNECTION = "mysql"
DB_HOST = "mysql.railway.internal"
DB_PORT = "3306"
DB_DATABASE = "railway"
DB_USERNAME = "root"
DB_PASSWORD = "cPDxqOVfmjurUKCuiYwokxJAcJnAKnzR"

# Session & Cache
SESSION_DRIVER = "database"
QUEUE_CONNECTION = "database"
CACHE_STORE = "database"

# Vite (React + Inertia)
VITE_APP_NAME = "${APP_NAME}"
VITE_APP_URL = "${APP_URL}"
