[build]
builder = "heroku/buildpacks:20"
installCommand = "composer install --no-dev && npm ci && npm run build"

[start]
command = "php artisan serve --host=0.0.0.0 --port=$PORT"



[env]
APP_NAME = "SEMS"
APP_ENV = "production"
APP_KEY = "base64:1B2t1SHJv3KuMDl6yNjSNERFaaAnzsAu9ZZc4TwxS50="
APP_DEBUG = "false"
APP_URL = "https://uddsems-production.up.railway.app"

# Database (Railway MySQL)
DB_CONNECTION = "mysql"
DB_HOST = "mysql.railway.internal"
DB_PORT = "3306"
DB_DATABASE = "railway"
DB_USERNAME = "root"
DB_PASSWORD = "cPDxqOVfmjurUKCuiYwokxJAcJnAKnzR"

# Session & Cache
SESSION_DRIVER = "database"
QUEUE_CONNECTION = "database"
CACHE_STORE = "database"

# Vite (React + Inertia)
VITE_APP_NAME = "${APP_NAME}"
VITE_APP_URL = "${APP_URL}"
