[build]
# Use Nixpacks to detect PHP + Node
builder = "heroku/php"

installCommand = "composer install --no-dev --optimize-autoloader && npm ci --omit=dev && npm run build"

[env]
APP_NAME = "Laravel"
APP_ENV = "production"
APP_KEY = "base64:PRMgg8BebBCOjKNOW2jG1DZ93EAON+FoDUgq5fQ8Gd8="
APP_DEBUG = "false"
APP_URL = "https://uddsems-production.up.railway.app"

DB_CONNECTION = "mysql"
DB_HOST = "mysql.railway.internal"
DB_PORT = "3306"
DB_DATABASE = "railway"
DB_USERNAME = "root"
DB_PASSWORD = "cPDxqOVfmjurUKCuiYwokxJAcJnAKnzR"

VITE_APP_NAME = "Laravel"
